const ebooksData = {

    ebooks: [
      {
        "id": 1,
        "author": "John Smith",
        "title": "The Adventure Begins",
        "price": 9.99,
        "description": "Join our heroes on a thrilling adventure filled with danger and excitement.",
        "publisher": "Adventure Books Ltd.",
        "pages": 320,
        "format": "PDF",
        "language": "English",
        "category": "Adventure",
        "publicationDate": "2023-07-15",
        "image": "https://example.com/images/adventure_book.jpg"
      },
      {
        "id": 2,
        "author": "Jane Doe",
        "title": "Mystery Mansion",
        "price": 7.99,
        "description": "Explore the secrets of the mysterious mansion in this gripping mystery novel.",
        "publisher": "Mystery Publishing Co.",
        "pages": 280,
        "format": "ePub",
        "language": "English",
        "category": "Mystery",
        "publicationDate": "2023-06-20",
        "image": "https://example.com/images/mystery_mansion.jpg"
      },
      {
        "id": 3,
        "author": "Emily Brown",
        "title": "Romantic Whispers",
        "price": 5.99,
        "description": "Experience the tender and passionate journey of love in this heartwarming romance.",
        "publisher": "Love Stories Press",
        "pages": 200,
        "format": "Kindle",
        "language": "English",
        "category": "Romance",
        "publicationDate": "2023-05-10",
        "image": "https://example.com/images/romantic_whispers.jpg"
      },
      {
        "id": 4,
        "author": "Michael Johnson",
        "title": "Sci-Fi Odyssey",
        "price": 12.99,
        "description": "Embark on a thrilling intergalactic adventure in this epic science fiction novel.",
        "publisher": "Space Books Inc.",
        "pages": 400,
        "format": "PDF",
        "language": "English",
        "category": "Science Fiction",
        "publicationDate": "2023-04-05",
        "image": "https://example.com/images/sci_fi_odyssey.jpg"
      },
      {
        "id": 5,
        "author": "David Lee",
        "title": "The Historical Quest",
        "price": 8.99,
        "description": "Discover the secrets of the past in this captivating historical fiction tale.",
        "publisher": "History Press",
        "pages": 350,
        "format": "ePub",
        "language": "English",
        "category": "Historical Fiction",
        "publicationDate": "2023-03-12",
        "image": "https://example.com/images/historical_quest.jpg"
      },
      {
        "id": 6,
        "author": "Anna Taylor",
        "title": "Fantasy Realms",
        "price": 10.99,
        "description": "Step into a world of magic and fantasy in this enchanting fantasy novel.",
        "publisher": "Fantasy Books Co.",
        "pages": 380,
        "format": "Kindle",
        "language": "English",
        "category": "Fantasy",
        "publicationDate": "2023-02-28",
        "image": "https://example.com/images/fantasy_realms.jpg"
      },
      {
        "id": 7,
        "author": "Robert Wilson",
        "title": "Thrilling Suspense",
        "price": 6.99,
        "description": "Get ready for heart-pounding suspense and unexpected twists in this gripping thriller.",
        "publisher": "Thriller Publishing",
        "pages": 270,
        "format": "PDF",
        "language": "English",
        "category": "Thriller",
        "publicationDate": "2023-01-18",
        "image": "https://example.com/images/thrilling_suspense.jpg"
      },
      {
        "id": 8,
        "author": "Emma White",
        "title": "Poetry in Motion",
        "price": 4.99,
        "description": "Experience the beauty of words and emotions in this collection of heartfelt poems.",
        "publisher": "Poetry Press",
        "pages": 150,
        "format": "ePub",
        "language": "English",
        "category": "Poetry",
        "publicationDate": "2022-12-05",
        "image": "https://example.com/images/poetry_in_motion.jpg"
      },
      {
        "id": 9,
        "author": "William Green",
        "title": "Educational Insights",
        "price": 11.99,
        "description": "Expand your knowledge and learn new insights in this enlightening educational book.",
        "publisher": "Knowledge Publishing",
        "pages": 420,
        "format": "PDF",
        "language": "English",
        "category": "Educational",
        "publicationDate": "2022-11-22",
        "image": "https://example.com/images/educational_insights.jpg"
      },
      {
        "id": 10,
        "author": "Sophia Clark",
        "title": "Healthy Habits",
        "price": 9.49,
        "description": "Discover the secrets to a healthy and balanced life in this wellness guide.",
        "publisher": "Wellness Books",
        "pages": 230,
        "format": "Kindle",
        "language": "English",
        "category": "Health & Wellness",
        "publicationDate": "2022-10-15",
        "image": "https://example.com/images/healthy_habits.jpg"
      },
      {
        "id": 11,
        "author": "Alice Roberts",
        "title": "Ancient Discoveries",
        "price": 8.99,
        "description": "Unravel the mysteries of ancient civilizations and their remarkable discoveries.",
        "publisher": "History Unearthed",
        "pages": 320,
        "format": "ePub",
        "language": "English",
        "category": "History",
        "publicationDate": "2023-07-19",
        "image": "https://example.com/images/ancient_discoveries.jpg"
      },
      {
        "id": 12,
        "author": "James Turner",
        "title": "Murder in the Mansion",
        "price": 6.49,
        "description": "Investigate a murder mystery in an opulent mansion with unexpected twists.",
        "publisher": "Mystery Novels",
        "pages": 280,
        "format": "PDF",
        "language": "English",
        "category": "Mystery",
        "publicationDate": "2023-06-18",
        "image": "https://example.com/images/murder_mansion.jpg"
      },
      {
        "id": 13,
        "author": "Sophie King",
        "title": "Love Beyond Time",
        "price": 5.49,
        "description": "Experience a timeless romance that transcends the boundaries of time.",
        "publisher": "Timeless Love Publishing",
        "pages": 200,
        "format": "Kindle",
        "language": "English",
        "category": "Romance",
        "publicationDate": "2023-05-15",
        "image": "https://example.com/images/love_beyond_time.jpg"
      },
      {
        "id": 14,
        "author": "Alex Turner",
        "title": "Parallel Universes",
        "price": 11.99,
        "description": "Journey through parallel universes in this mind-bending sci-fi adventure.",
        "publisher": "Cosmic Books",
        "pages": 400,
        "format": "ePub",
        "language": "English",
        "category": "Science Fiction",
        "publicationDate": "2023-04-12",
        "image": "https://example.com/images/parallel_universes.jpg"
      },
      {
        "id": 15,
        "author": "Isabella Reed",
        "title": "The Enchanted Garden",
        "price": 9.99,
        "description": "Step into an enchanted garden filled with magical creatures and wonders.",
        "publisher": "Fantasy Tales",
        "pages": 350,
        "format": "Kindle",
        "language": "English",
        "category": "Fantasy",
        "publicationDate": "2023-03-09",
        "image": "https://example.com/images/enchanted_garden.jpg"
      },
      {
        "id": 16,
        "author": "Robert Johnson",
        "title": "The Vanishing Act",
        "price": 7.99,
        "description": "Solve the disappearance of a famous magician in this captivating thriller.",
        "publisher": "Suspenseful Reads",
        "pages": 270,
        "format": "PDF",
        "language": "English",
        "category": "Thriller",
        "publicationDate": "2023-02-06",
        "image": "https://example.com/images/vanishing_act.jpg"
      },
      {
        "id": 17,
        "author": "Emily Collins",
        "title": "Whispers of the Soul",
        "price": 4.99,
        "description": "Delve into the depths of emotions through poetic whispers of the soul.",
        "publisher": "Soulful Poetry",
        "pages": 150,
        "format": "ePub",
        "language": "English",
        "category": "Poetry",
        "publicationDate": "2022-12-31",
        "image": "https://example.com/images/whispers_of_soul.jpg"
      },
      {
        "id": 18,
        "author": "Michael Brown",
        "title": "The Human Odyssey",
        "price": 12.99,
        "description": "Embark on a captivating journey through human evolution and history.",
        "publisher": "Knowledge Seekers",
        "pages": 420,
        "format": "PDF",
        "language": "English",
        "category": "Educational",
        "publicationDate": "2022-11-27",
        "image": "https://example.com/images/human_odyssey.jpg"
      },
      {
        "id": 19,
        "author": "Olivia Smith",
        "title": "Mindful Living",
        "price": 9.49,
        "description": "Embrace mindfulness and live a fulfilling life with inner peace and balance.",
        "publisher": "Mindfulness Guides",
        "pages": 230,
        "format": "Kindle",
        "language": "English",
        "category": "Health & Wellness",
        "publicationDate": "2022-10-24",
        "image": "https://example.com/images/mindful_living.jpg"
      },
      {
        "id": 20,
        "author": "Lucas Parker",
        "title": "Exploring the Cosmos",
        "price": 7.99,
        "description": "Embark on a cosmic journey and explore the wonders of the universe.",
        "publisher": "Cosmic Explorers",
        "pages": 320,
        "format": "ePub",
        "language": "English",
        "category": "Science",
        "publicationDate": "2022-09-18",
        "image": "https://example.com/images/exploring_cosmos.jpg"
      }
    ]
  };

  export default ebooksData;